// Wails v2 auto-generated TypeScript bindings for App.
// This file is regenerated by `wails dev` / `wails build`.

export function GetVersion(): Promise<string>;
export function OpenURL(url: string): Promise<undefined>;
export function SaveFile(defaultName: string, contents: number[]): Promise<void>;
export function BackupDatabase(): Promise<string>;
export function RestoreDatabase(): Promise<string>;

// Clients
export function GetClients(organizationId: string): Promise<any[]>;
export function GetClient(clientId: string): Promise<any>;
export function CreateClient(req: any): Promise<any>;
export function UpdateClient(clientId: string, updates: any): Promise<any>;
export function DeleteClient(clientId: string): Promise<boolean>;
export function GetClientInvoiceCount(clientId: string): Promise<number>;

// Invoices
export function GetInvoices(organizationId: string): Promise<any[]>;
export function GetInvoice(invoiceId: string): Promise<any>;
export function GetInvoiceLineItems(invoiceId: string): Promise<any[]>;
export function CreateInvoice(req: any): Promise<any>;
export function UpdateInvoice(invoiceId: string, updates: any): Promise<any>;
export function UpdateInvoiceState(invoiceId: string, state: string): Promise<any>;
export function DeleteInvoice(invoiceId: string): Promise<boolean>;

// Organizations
export function GetOrganizations(): Promise<any[]>;
export function GetOrganization(organizationId: string): Promise<any>;
export function CreateOrganization(req: any): Promise<any>;
export function UpdateOrganization(organizationId: string, updates: any): Promise<any>;
export function DeleteOrganization(organizationId: string): Promise<boolean>;

// Tax Rates
export function GetTaxRates(organizationId: string): Promise<any[]>;
export function GetTaxRate(taxRateId: string): Promise<any>;
export function CreateTaxRate(req: any): Promise<any>;
export function UpdateTaxRate(taxRateId: string, updates: any): Promise<any>;
export function DeleteTaxRate(taxRateId: string): Promise<boolean>;

// Tags
export function GetTags(organizationId: string): Promise<any[]>;
export function GetTag(tagId: string): Promise<any>;
export function CreateTag(req: any): Promise<any>;
export function UpdateTag(tagId: string, updates: any): Promise<any>;
export function DeleteTag(tagId: string): Promise<boolean>;

// Time Entries
export function GetTimeEntries(organizationId: string): Promise<any[]>;
export function GetTimeEntry(timeEntryId: string): Promise<any>;
export function CreateTimeEntry(req: any): Promise<any>;
export function UpdateTimeEntry(timeEntryId: string, updates: any): Promise<any>;
export function DeleteTimeEntry(timeEntryId: string): Promise<boolean>;

// Projects
export function GetProjects(organizationId: string): Promise<any[]>;
export function GetProject(projectId: string): Promise<any>;
export function CreateProject(req: any): Promise<any>;
export function UpdateProject(projectId: string, updates: any): Promise<any>;
export function DeleteProject(projectId: string): Promise<boolean>;
