// Wails v2 auto-generated JavaScript bindings for App.
// This file is regenerated by `wails dev` / `wails build`.
// DO NOT EDIT — run `wails dev` to regenerate with correct method IDs.

'use strict';

/**
 * Calls a bound Go method by name via the Wails runtime.
 * The generated version uses ByID (faster). This stub uses the runtime's
 * named dispatch so it works before the first `wails dev` run.
 */
function call(method, ...args) {
  // window['go']['main']['App'] is populated by the Wails backend at startup.
  return window['go']['main']['App'][method](...args);
}

export function GetVersion() { return call('GetVersion'); }
export function OpenURL($0) { return call('OpenURL', $0); }
export function SaveFile($0, $1) { return call('SaveFile', $0, $1); }
export function BackupDatabase() { return call('BackupDatabase'); }
export function RestoreDatabase() { return call('RestoreDatabase'); }

// Clients
export function GetClients($0) { return call('GetClients', $0); }
export function GetClient($0) { return call('GetClient', $0); }
export function CreateClient($0) { return call('CreateClient', $0); }
export function UpdateClient($0, $1) { return call('UpdateClient', $0, $1); }
export function DeleteClient($0) { return call('DeleteClient', $0); }
export function GetClientInvoiceCount($0) { return call('GetClientInvoiceCount', $0); }

// Invoices
export function GetInvoices($0) { return call('GetInvoices', $0); }
export function GetInvoice($0) { return call('GetInvoice', $0); }
export function GetInvoiceLineItems($0) { return call('GetInvoiceLineItems', $0); }
export function CreateInvoice($0) { return call('CreateInvoice', $0); }
export function UpdateInvoice($0, $1) { return call('UpdateInvoice', $0, $1); }
export function UpdateInvoiceState($0, $1) { return call('UpdateInvoiceState', $0, $1); }
export function DeleteInvoice($0) { return call('DeleteInvoice', $0); }

// Organizations
export function GetOrganizations() { return call('GetOrganizations'); }
export function GetOrganization($0) { return call('GetOrganization', $0); }
export function CreateOrganization($0) { return call('CreateOrganization', $0); }
export function UpdateOrganization($0, $1) { return call('UpdateOrganization', $0, $1); }
export function DeleteOrganization($0) { return call('DeleteOrganization', $0); }

// Tax Rates
export function GetTaxRates($0) { return call('GetTaxRates', $0); }
export function GetTaxRate($0) { return call('GetTaxRate', $0); }
export function CreateTaxRate($0) { return call('CreateTaxRate', $0); }
export function UpdateTaxRate($0, $1) { return call('UpdateTaxRate', $0, $1); }
export function DeleteTaxRate($0) { return call('DeleteTaxRate', $0); }

// Tags
export function GetTags($0) { return call('GetTags', $0); }
export function GetTag($0) { return call('GetTag', $0); }
export function CreateTag($0) { return call('CreateTag', $0); }
export function UpdateTag($0, $1) { return call('UpdateTag', $0, $1); }
export function DeleteTag($0) { return call('DeleteTag', $0); }

// Time Entries
export function GetTimeEntries($0) { return call('GetTimeEntries', $0); }
export function GetTimeEntry($0) { return call('GetTimeEntry', $0); }
export function CreateTimeEntry($0) { return call('CreateTimeEntry', $0); }
export function UpdateTimeEntry($0, $1) { return call('UpdateTimeEntry', $0, $1); }
export function DeleteTimeEntry($0) { return call('DeleteTimeEntry', $0); }

// Projects
export function GetProjects($0) { return call('GetProjects', $0); }
export function GetProject($0) { return call('GetProject', $0); }
export function CreateProject($0) { return call('CreateProject', $0); }
export function UpdateProject($0, $1) { return call('UpdateProject', $0, $1); }
export function DeleteProject($0) { return call('DeleteProject', $0); }
