// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function CreateOrganization(arg1) {
  return window['go']['main']['App']['CreateOrganization'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function CreateTaxRate(arg1) {
  return window['go']['main']['App']['CreateTaxRate'](arg1);
}

export function CreateTimeEntry(arg1) {
  return window['go']['main']['App']['CreateTimeEntry'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteInvoice(arg1) {
  return window['go']['main']['App']['DeleteInvoice'](arg1);
}

export function DeleteOrganization(arg1) {
  return window['go']['main']['App']['DeleteOrganization'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTaxRate(arg1) {
  return window['go']['main']['App']['DeleteTaxRate'](arg1);
}

export function DeleteTimeEntry(arg1) {
  return window['go']['main']['App']['DeleteTimeEntry'](arg1);
}

export function GetClient(arg1) {
  return window['go']['main']['App']['GetClient'](arg1);
}

export function GetClientInvoiceCount(arg1) {
  return window['go']['main']['App']['GetClientInvoiceCount'](arg1);
}

export function GetClients(arg1) {
  return window['go']['main']['App']['GetClients'](arg1);
}

export function GetInvoice(arg1) {
  return window['go']['main']['App']['GetInvoice'](arg1);
}

export function GetInvoiceLineItems(arg1) {
  return window['go']['main']['App']['GetInvoiceLineItems'](arg1);
}

export function GetInvoices(arg1) {
  return window['go']['main']['App']['GetInvoices'](arg1);
}

export function GetOrganization(arg1) {
  return window['go']['main']['App']['GetOrganization'](arg1);
}

export function GetOrganizations() {
  return window['go']['main']['App']['GetOrganizations']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects(arg1) {
  return window['go']['main']['App']['GetProjects'](arg1);
}

export function GetTag(arg1) {
  return window['go']['main']['App']['GetTag'](arg1);
}

export function GetTags(arg1) {
  return window['go']['main']['App']['GetTags'](arg1);
}

export function GetTaxRate(arg1) {
  return window['go']['main']['App']['GetTaxRate'](arg1);
}

export function GetTaxRates(arg1) {
  return window['go']['main']['App']['GetTaxRates'](arg1);
}

export function GetTimeEntries(arg1) {
  return window['go']['main']['App']['GetTimeEntries'](arg1);
}

export function GetTimeEntry(arg1) {
  return window['go']['main']['App']['GetTimeEntry'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RestoreDatabase() {
  return window['go']['main']['App']['RestoreDatabase']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function UpdateClient(arg1, arg2) {
  return window['go']['main']['App']['UpdateClient'](arg1, arg2);
}

export function UpdateInvoice(arg1, arg2) {
  return window['go']['main']['App']['UpdateInvoice'](arg1, arg2);
}

export function UpdateInvoiceState(arg1, arg2) {
  return window['go']['main']['App']['UpdateInvoiceState'](arg1, arg2);
}

export function UpdateOrganization(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrganization'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateTag(arg1, arg2) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2);
}

export function UpdateTaxRate(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaxRate'](arg1, arg2);
}

export function UpdateTimeEntry(arg1, arg2) {
  return window['go']['main']['App']['UpdateTimeEntry'](arg1, arg2);
}
