// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function BackupDatabase():Promise<string>;

export function CreateClient(arg1:db.CreateClientRequest):Promise<db.Client>;

export function CreateInvoice(arg1:db.CreateInvoiceRequest):Promise<db.Invoice>;

export function CreateOrganization(arg1:db.CreateOrganizationRequest):Promise<db.Organization>;

export function CreateProject(arg1:db.CreateProjectRequest):Promise<db.Project>;

export function CreateTag(arg1:db.CreateTagRequest):Promise<db.Tag>;

export function CreateTaxRate(arg1:db.CreateTaxRateRequest):Promise<db.TaxRate>;

export function CreateTimeEntry(arg1:db.CreateTimeEntryRequest):Promise<db.TimeEntry>;

export function DeleteClient(arg1:string):Promise<boolean>;

export function DeleteInvoice(arg1:string):Promise<boolean>;

export function DeleteOrganization(arg1:string):Promise<boolean>;

export function DeleteProject(arg1:string):Promise<boolean>;

export function DeleteTag(arg1:string):Promise<boolean>;

export function DeleteTaxRate(arg1:string):Promise<boolean>;

export function DeleteTimeEntry(arg1:string):Promise<boolean>;

export function GetClient(arg1:string):Promise<db.Client>;

export function GetClientInvoiceCount(arg1:string):Promise<number>;

export function GetClients(arg1:string):Promise<Array<db.Client>>;

export function GetInvoice(arg1:string):Promise<db.Invoice>;

export function GetInvoiceLineItems(arg1:string):Promise<Array<db.InvoiceLineItem>>;

export function GetInvoices(arg1:string):Promise<Array<db.Invoice>>;

export function GetOrganization(arg1:string):Promise<db.Organization>;

export function GetOrganizations():Promise<Array<db.Organization>>;

export function GetProject(arg1:string):Promise<db.Project>;

export function GetProjects(arg1:string):Promise<Array<db.Project>>;

export function GetTag(arg1:string):Promise<db.Tag>;

export function GetTags(arg1:string):Promise<Array<db.Tag>>;

export function GetTaxRate(arg1:string):Promise<db.TaxRate>;

export function GetTaxRates(arg1:string):Promise<Array<db.TaxRate>>;

export function GetTimeEntries(arg1:string):Promise<Array<db.TimeEntry>>;

export function GetTimeEntry(arg1:string):Promise<db.TimeEntry>;

export function GetVersion():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function RestoreDatabase():Promise<string>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function UpdateClient(arg1:string,arg2:db.UpdateClientRequest):Promise<db.Client>;

export function UpdateInvoice(arg1:string,arg2:db.UpdateInvoiceRequest):Promise<db.Invoice>;

export function UpdateInvoiceState(arg1:string,arg2:string):Promise<db.Invoice>;

export function UpdateOrganization(arg1:string,arg2:db.UpdateOrganizationRequest):Promise<db.Organization>;

export function UpdateProject(arg1:string,arg2:db.UpdateProjectRequest):Promise<db.Project>;

export function UpdateTag(arg1:string,arg2:db.UpdateTagRequest):Promise<db.Tag>;

export function UpdateTaxRate(arg1:string,arg2:db.UpdateTaxRateRequest):Promise<db.TaxRate>;

export function UpdateTimeEntry(arg1:string,arg2:db.UpdateTimeEntryRequest):Promise<db.TimeEntry>;
